-- Create the products table
CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    image_url VARCHAR(255),
    ai_hint VARCHAR(255),
    href VARCHAR(255) UNIQUE,
    category VARCHAR(50) CHECK(category IN ('pc', 'ios', 'android'))
);

-- Insert data for PC products
INSERT INTO products (name, price, image_url, ai_hint, href, category) VALUES
('Vnhax Frozen Key', 5, 'https://i.postimg.cc/j5QRy4fy/Vnhax-frozen-key.jpg', 'abstract green', '/products/vnhax-frozen-key', 'pc'),
('Vnhax Week Key', 15, 'https://i.postimg.cc/26Mvsmyz/Vnhax-week-key.jpg', 'abstract purple', '/products/vnhax-week-key', 'pc'),
('Vnhax Month Key', 30, 'https://i.postimg.cc/cJ1bH7mv/Vnhax-month-key.jpg', 'abstract blue', '/products/vnhax-month-key', 'pc'),
('Vnhax Admin Key', 190, 'https://i.postimg.cc/QdYpQpD9/Vnhax-Admin-key.jpg', 'abstract gold', '/products/vnhax-admin-key', 'pc'),
('Redeye Frozen Key', 5, 'https://i.postimg.cc/JhTnsWfj/Redeye-frozen-key.jpg', 'abstract dark red', '/products/redeye-frozen-key', 'pc'),
('Redeye Week Key', 15, 'https://i.postimg.cc/rwVMxPCj/Redeye-week-key.jpg', 'abstract fire', '/products/redeye-week-key', 'pc'),
('Redeye Month Key', 30, 'https://i.postimg.cc/8PDSg03G/Redeye-month-key.jpg', 'abstract red', '/products/redeye-month-key', 'pc'),
('Anubis Week Key', 20, 'https://i.postimg.cc/3N60d0qM/Anubis-week-key.jpg', 'abstract sand', '/products/anubis-week-key', 'pc'),
('Anubis Month Key', 40, 'https://i.postimg.cc/Gh8s6zBb/Anubis-month-key.jpg', 'abstract gold', '/products/anubis-month-key', 'pc');

-- Insert data for iOS products
INSERT INTO products (name, price, image_url, ai_hint, href, category) VALUES
('Vnhax iOS Frozen Key', 5, 'https://i.postimg.cc/k4WLbYWy/vn-ios-frozen-key.jpg', 'gaming character cinematic', '/products/vnhax-ios-frozen-key', 'ios'),
('Vnhax iOS Week Key', 15, 'https://i.postimg.cc/J404Fh2J/vn-ios-week-key.jpg', 'gaming character cinematic', '/products/vnhax-ios-week-key', 'ios'),
('Vnhax iOS Month Key', 30, 'https://i.postimg.cc/yYGYCzMG/vn-ios-month-key.jpg', 'gaming character cinematic', '/products/vnhax-ios-month-key', 'ios'),
('Star iOS Frozen Key', 5, 'https://i.postimg.cc/SxKT8Bjm/star-ios-frozen-key.jpg', 'gaming character cinematic', '/products/star-ios-frozen-key', 'ios'),
('Star iOS Week Key', 15, 'https://i.postimg.cc/6pS0ZTDh/star-ios-week-key.jpg', 'gaming character cinematic', '/products/star-ios-week-key', 'ios'),
('Star iOS Month Key', 30, 'https://i.postimg.cc/9Qq9vbnG/star-ios-month-key.jpg', 'gaming character cinematic', '/products/star-ios-month-key', 'ios'),
('Tornado iOS Week Key', 17, 'https://i.postimg.cc/MpXs95F7/tornado-ios-week-key.jpg', 'gaming character cinematic', '/products/tornado-ios-week-key', 'ios'),
('Tornado iOS Month Key', 35, 'https://i.postimg.cc/KjJNN37p/tornado-ios-month-key.jpg', 'gaming character cinematic', '/products/tornado-ios-month-key', 'ios');

-- Insert data for Android products
INSERT INTO products (name, price, image_url, ai_hint, href, category) VALUES
('Shield Android Day Key', 5, 'https://i.postimg.cc/GhjRky3C/SHIELD-Android-day-key.jpg', 'gaming character cinematic', '/products/shield-android-day-key', 'android'),
('Shield Android Week Key', 15, 'https://i.postimg.cc/Gptb3mC1/SHIELD-Android-week-key.jpg', 'gaming character cinematic', '/products/shield-android-week-key', 'android'),
('Shield Android Month Key', 30, 'https://i.postimg.cc/Hxj1mZbW/SHIELD-Android-month-key.jpg', 'gaming character cinematic', '/products/shield-android-month-key', 'android'),
('Zolo Android Day Key', 5, 'https://i.postimg.cc/kGGfpL39/ZOLO-ios-day-key.jpg', 'gaming character cinematic', '/products/zolo-android-day-key', 'android'),
('Zolo Android Week Key', 15, 'https://i.postimg.cc/YStNPTYV/ZOLO-ios-month-key-1.jpg', 'gaming character cinematic', '/products/zolo-android-week-key', 'android'),
('Zolo Android Month Key', 30, 'https://i.postimg.cc/qBc3P1MH/ZOLO-ios-month-key.jpg', 'gaming character cinematic', '/products/zolo-android-month-key', 'android'),
('Kernel Root Android Week Key', 20, 'https://i.postimg.cc/NjV8sb9G/Kernel-Android-week-key.jpg', 'gaming character cinematic', '/products/kernel-android-week-key', 'android'),
('Kernel Root Android Month Key', 40, 'https://i.postimg.cc/C1Jz1LPC/Kernel-Android-month-key.jpg', 'gaming character cinematic', '/products/kernel-android-month-key', 'android');

-- Create the courses table
CREATE TABLE courses (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    learning_objectives TEXT[],
    modules JSONB,
    banner_url VARCHAR(255),
    href VARCHAR(255) UNIQUE
);

-- Insert data for courses
INSERT INTO courses (title, description, learning_objectives, modules, banner_url, href) VALUES
('Adobe After Effects for Beginners', 'Bring your creative ideas to life with Adobe After Effects. This course will teach you the fundamentals of motion graphics and visual effects, from basic animations to complex compositions.', ARRAY['Navigate the After Effects interface and workflow.', 'Create animations using keyframes, shapes, and text.', 'Understand and apply visual effects and presets.', 'Work with masks, mattes, and compositing techniques.', 'Learn the basics of 3D space and camera movement.', 'Render and export your projects for various platforms.'], '[{"title": "Getting Started", "description": "Understanding the workspace and basic tools."}, {"title": "Animation Principles", "description": "Bringing motion to life with keyframes."}, {"title": "Shape Layers and Text Animation", "description": "Creating dynamic graphic elements."}, {"title": "Visual Effects and Compositing", "description": "Adding magic to your videos."}, {"title": "Working in 3D Space", "description": "Creating depth and perspective."}, {"title": "Rendering and Exporting", "description": "Sharing your work with the world."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/after-effects'),
('AI-Powered Coding', 'Supercharge your development workflow with AI tools. Learn how to use AI code assistants, generate code from prompts, debug with AI, and automate repetitive coding tasks to become a 10x developer.', ARRAY['Master AI code completion tools like GitHub Copilot.', 'Write effective prompts to generate functional code.', 'Use AI for code explanation, refactoring, and optimization.', 'Leverage AI for automated testing and debugging.', 'Integrate AI into your CI/CD pipeline.', 'Understand the future of software development with AI.'], '[{"title": "Introduction to AI Code Assistants", "description": "Getting started with tools like Copilot."}, {"title": "Prompt-Driven Development", "description": "Generating code from natural language."}, {"title": "AI-Assisted Debugging", "description": "Finding and fixing bugs faster."}, {"title": "Code Refactoring and Optimization", "description": "Improving code quality with AI."}, {"title": "Automated Testing with AI", "description": "Generating test cases automatically."}, {"title": "The Future of AI in Software Engineering", "description": "What to expect next."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/ai-coding'),
('Monetizing AI Skills', 'Learn how to turn your AI knowledge into a profitable venture. This course covers freelancing, building AI-powered SaaS products, consulting, and creating content to monetize your expertise.', ARRAY['Identify profitable niches in the AI industry.', 'Price your AI services and products effectively.', 'Find clients and projects as an AI freelancer.', 'Develop and launch a simple AI-powered SaaS application.', 'Build a personal brand as an AI expert.', 'Create and sell AI-related digital products or courses.'], '[{"title": "The AI Gold Rush", "description": "Opportunities for monetization in the AI space."}, {"title": "AI Freelancing and Consulting", "description": "Selling your skills to businesses."}, {"title": "Building and Selling AI SaaS", "description": "From idea to recurring revenue."}, {"title": "Creating AI-Powered Content", "description": "Monetizing your knowledge through content."}, {"title": "Marketing for AI Ventures", "description": "How to attract customers and clients."}, {"title": "Ethical Considerations", "description": "Building a sustainable and responsible AI business."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/ai-money'),
('Mastering CSS', 'Unlock the full potential of web styling with our comprehensive CSS course. From fundamentals to advanced animations, you will learn how to create beautiful and responsive websites.', ARRAY['Understand CSS syntax, selectors, and the cascade.', 'Master the box model, positioning, and layout techniques.', 'Learn Flexbox and Grid for modern, responsive designs.', 'Create stunning animations and transitions.', 'Apply best practices for writing clean and maintainable CSS.', 'Explore advanced topics like variables and pre-processors.'], '[{"title": "Introduction to CSS", "description": "The basics of CSS and how it works with HTML."}, {"title": "Selectors and Specificity", "description": "Targeting elements with precision."}, {"title": "The Box Model", "description": "Understanding margins, padding, and borders."}, {"title": "Layouts with Flexbox", "description": "Building flexible and responsive layouts."}, {"title": "Advanced Grid Systems", "description": "Mastering two-dimensional layouts."}, {"title": "Transitions and Animations", "description": "Bringing your web pages to life."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/css'),
('Deepseek: Advanced Search & Analysis', 'Master the art of advanced search and data analysis with Deepseek. This course covers powerful query techniques, data extraction, pattern recognition, and leveraging AI for deep insights.', ARRAY['Construct complex search queries for precise results.', 'Extract and structure data from unstructured sources.', 'Use AI-powered tools for sentiment analysis and topic modeling.', 'Identify trends and patterns in large datasets.', 'Automate research and data gathering tasks.', 'Apply your skills to business intelligence and research.'], '[{"title": "The Art of the Query", "description": "Beyond basic keyword searching."}, {"title": "Data Extraction Techniques", "description": "Scraping and parsing data from the web."}, {"title": "AI-Powered Text Analysis", "description": "Understanding text data at scale."}, {"title": "Pattern Recognition", "description": "Finding hidden insights in your data."}, {"title": "Automating Research Workflows", "description": "Building tools to gather information."}, {"title": "Practical Applications", "description": "Case studies in market research and OSINT."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/deepseek'),
('Generative AI Fundamentals', 'Dive into the fascinating world of Generative AI. Learn the principles behind large language models (LLMs), diffusion models for image generation, and how to build applications with them.', ARRAY['Understand the core concepts of generative models.', 'Learn how LLMs like GPT work.', 'Explore text generation, summarization, and translation.', 'Understand image generation with models like DALL-E and Stable Diffusion.', 'Learn prompt engineering techniques for better results.', 'Build a simple generative AI application.'], '[{"title": "Introduction to Generative AI", "description": "What is it and why is it important?"}, {"title": "Large Language Models (LLMs)", "description": "The technology behind ChatGPT."}, {"title": "Prompt Engineering", "description": "Getting the most out of AI models."}, {"title": "Image Generation Models", "description": "Creating art and images from text."}, {"title": "Building with AI APIs", "description": "Integrating generative AI into your projects."}, {"title": "The Future of AI", "description": "Exploring the ethics and future trends."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/gen-ai'),
('Advanced HTML5', 'Go beyond the basics and master the full power of HTML5. This course covers semantic markup, accessibility, multimedia integration, and modern APIs to build structured and meaningful web content.', ARRAY['Write clean, semantic, and accessible HTML.', 'Integrate audio, video, and interactive elements.', 'Understand and use the Canvas API for graphics.', 'Work with modern form controls and validation.', 'Learn about Web Storage, Geolocation, and other APIs.', 'Optimize HTML for performance and SEO.'], '[{"title": "Semantic HTML", "description": "Structuring your content for meaning."}, {"title": "Multimedia Elements", "description": "Embedding audio and video."}, {"title": "Advanced Forms", "description": "Creating interactive and accessible forms."}, {"title": "Canvas and SVG", "description": "Drawing graphics on the web."}, {"title": "Web APIs", "description": "Using browser APIs like Geolocation and Web Storage."}, {"title": "Accessibility (a11y)", "description": "Making your websites usable for everyone."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/html'),
('JavaScript: The Advanced Concepts', 'Move beyond the fundamentals and master the core concepts of JavaScript. This course dives deep into closures, promises, async/await, prototypes, and modern ES6+ features.', ARRAY['Gain a deep understanding of the JavaScript event loop.', 'Master asynchronous programming with Promises and async/await.', 'Understand closures, scope, and execution context.', 'Learn about prototypal inheritance and object-oriented patterns.', 'Work with modern data structures like Maps and Sets.', 'Write clean, efficient, and modern JavaScript code.'], '[{"title": "Asynchronous JavaScript", "description": "Callbacks, Promises, and Async/Await."}, {"title": "Core Concepts", "description": "Closures, Scope, and Hoisting."}, {"title": "Object-Oriented JavaScript", "description": "Prototypes, Classes, and Inheritance."}, {"title": "Functional Programming", "description": "Immutability, Pure Functions, and Higher-Order Functions."}, {"title": "Modern ES6+ Features", "description": "Destructuring, Spread/Rest, and Modules."}, {"title": "JavaScript Engine and Runtime", "description": "How JavaScript works under the hood."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/javascript'),
('Adobe Premiere Pro Fundamentals', 'Learn professional video editing with Adobe Premiere Pro. This course covers the entire workflow from importing footage and creating sequences to color correction, audio mixing, and exporting.', ARRAY['Master the Premiere Pro interface and editing tools.', 'Organize and manage your media effectively.', 'Learn cutting, trimming, and sequencing techniques.', 'Apply transitions, effects, and color correction.', 'Edit and mix audio like a pro.', 'Export high-quality video for any platform.'], '[{"title": "Introduction to Premiere Pro", "description": "Navigating the workspace and importing media."}, {"title": "The Editing Workflow", "description": "From rough cut to fine cut."}, {"title": "Working with Audio", "description": "Mixing sound and adding music."}, {"title": "Color Correction and Grading", "description": "Creating a cinematic look."}, {"title": "Titles, Graphics, and Effects", "description": "Adding professional polish."}, {"title": "Exporting and Sharing", "description": "Delivering your final video."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/premiere-pro'),
('Shopify E-commerce Blueprint', 'Build a successful online store from scratch with Shopify. This course guides you through store setup, product sourcing, theme customization, marketing, and scaling your e-commerce business.', ARRAY['Set up and configure a Shopify store.', 'Find and add winning products to your store.', 'Customize your store theme to match your brand.', 'Implement effective marketing and SEO strategies.', 'Manage orders, shipping, and customer service.', 'Analyze your store data to scale your business.'], '[{"title": "Getting Started with Shopify", "description": "Setting up your account and store."}, {"title": "Product and Collection Management", "description": "Sourcing and organizing your products."}, {"title": "Theme Customization and Branding", "description": "Creating a beautiful storefront."}, {"title": "Marketing and Sales Channels", "description": "Driving traffic and making sales."}, {"title": "Order Fulfillment and Customer Service", "description": "Managing the day-to-day operations."}, {"title": "Analytics and Scaling", "description": "Using data to grow your empire."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/shopify'),
('TikTok Content Creation Mastery', 'Learn the secrets to creating viral content on TikTok. This course covers everything from finding trends and shooting engaging videos to mastering the algorithm and growing your audience.', ARRAY['Understand the TikTok algorithm and how to use it to your advantage.', 'Identify and capitalize on viral trends.', 'Master video shooting, editing, and effects within the app.', 'Develop a content strategy that builds a loyal following.', 'Collaborate with other creators and brands.', 'Monetize your TikTok presence effectively.'], '[{"title": "Understanding the TikTok Ecosystem", "description": "Navigating the platform and its culture."}, {"title": "Content Strategy and Ideation", "description": "Planning your content for maximum impact."}, {"title": "Shooting and Editing Techniques", "description": "Creating high-quality, engaging videos."}, {"title": "Growth Hacking the Algorithm", "description": "Tips and tricks to go viral."}, {"title": "Monetization and Brand Deals", "description": "Turning your passion into a career."}]'::jsonb, 'https://picsum.photos/600/400', '/courses/tiktok');
